# Generated by Django 4.1.2 on 2022-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_from', models.IntegerField()),
                ('experience_to', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
    ]
