# Generated by Django 4.1.2 on 2022-10-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_name', models.CharField(max_length=120)),
                ('achieve_descr', models.TextField()),
            ],
        ),
    ]
