# Generated by Django 4.1.2 on 2022-10-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_achieve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
