# Generated by Django 4.1.2 on 2022-10-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_experience_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achieve',
            new_name='Achievement',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='achieve_descr',
            new_name='achievement_descr',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='achieve_name',
            new_name='achievement_name',
        ),
    ]
