# Generated by Django 4.1.2 on 2022-10-07 20:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_alter_task_responsible'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentEmployee',
            new_name='DepartmentStaff',
        ),
    ]
