# Generated by Django 4.1.2 on 2022-10-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employee_experience_employee_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_from', models.IntegerField()),
                ('experience_to', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
    ]
