# Generated by Django 4.1.2 on 2022-10-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_subordinates_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
