# Generated by Django 4.1.2 on 2022-10-08 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_achieve_achievement_and_more'),
        ('user', '0006_delete_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='game.achievement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
